/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('primevue/card')['default']
    Panel: typeof import('primevue/panel')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
  }
}
